name: Prebuild workflow
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu latest
    steps: 
      - name: Get code from repo
        uses: action/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test